version: 2
updates:
  # JavaScript dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5

  # Rust dependencies
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
