[package]
name = "test-overlaps"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test-overlaps"
path = "src/main.rs"

[[bin]]
name = "test-regions"
path = "src/test_regions.rs"

[dependencies]
grep-regex = "0.1"
grep-searcher = "0.1"
grep-matcher = "0.1"
